<a href="https://colab.research.google.com/github/Tanusri04/Hugging_Face_Projects/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
a = torch.tensor([[7, 7],
                  [7, 7]])
a.shape

torch.Size([2, 2])

In [ ]:
a = torch.tensor([[1, 7], [9, 8]])
a.ndim

2

In [ ]:
a[1][0]

tensor(9)

In [ ]:
#Used for images
a = torch.rand(size = (233, 233, 3)) # height, width, colour (RGB)
a.ndim, a.shape

(3, torch.Size([233, 233, 3]))

In [ ]:
#Zeros and ones
a = torch.ones(1, 3)
b = torch.zeros(2, 4, dtype = torch.float16) #default = float32
b, a, a.dtype, b.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]], dtype=torch.float16),
 tensor([[1., 1., 1.]]),
 torch.float32,
 torch.float16)

In [ ]:
#arange functions
a = torch.arange(start = 0, end = 50, step = 5) #default step size = 1
a


tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Tensors like
tensors_like = torch.ones_like(input = a)
tensors_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
x = torch.tensor([3, 4, 5],
          dtype = None,
          device = 'cpu',
          requires_grad = False) #for tracking gradients

x = x.type(torch.half) #to change data types from one to another
x

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.rand(3, 1)
print(y)
torch.matmul(x, x) #matrix multiplication
# OR
print(x @ x)
# OR use torch.mm

tensor([[0.6820],
        [0.0041],
        [0.5717]])
tensor(14)


In [ ]:
#transpose of a matrix
y = y.T
y

tensor([[0.6820, 0.0041, 0.5717]])

In [ ]:
#minimum value
torch.min(x)
x.min()

#maximum value
torch.max(y)
y.max()

#average value which only works with floating, complex values
torch.mean(y)
x.type(torch.float32).mean()

#sum
torch.sum(x), x.sum()

#position of minimum/maximum value in a tensor
torch.argmin(x)
x.argmax()


tensor(2)

In [ ]:
x = torch.tensor([1, 2, 3])
#re-shape
x_reshape = torch.reshape(x, (3, 1))
x_reshape

#view makes the changes in the original memory
z = x.view(3, 1)
z[0, 0] = 4
z, x


(tensor([[4],
         [2],
         [3]]),
 tensor([4, 2, 3]))

In [ ]:
#stack a tensor
stacked = torch.stack([x, x, x], dim = 1) #dimension depends on the shape of the tensor
print(stacked)

tensor([[4, 4, 4],
        [2, 2, 2],
        [3, 3, 3]])


In [ ]:
#squeeze removes single dimensions
x = torch.tensor([[1, 2, 3, 4]])
print(f"Shape of x: {x.shape}")
print(x)
x_squeezed = x.squeeze()
print(f"Shape of squeezed x: {x_squeezed.shape}")
print(x_squeezed)

#unsqueeze adds a dimension
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed, x_unsqueezed.shape

Shape of x: torch.Size([1, 4])
tensor([[1, 2, 3, 4]])
Shape of squeezed x: torch.Size([4])
tensor([1, 2, 3, 4])


(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [ ]:
#permute - change the order of the dimensions
original = torch.rand(2, 3, 4)
print(original)
print(original.shape)
new = torch.permute(original, (1, 0, 2)) # (3, 2, 4)
new, new.shape

tensor([[[0.6284, 0.0808, 0.8971, 0.6637],
         [0.9646, 0.8398, 0.2106, 0.5712],
         [0.2331, 0.9309, 0.0588, 0.7270]],

        [[0.6571, 0.1105, 0.9925, 0.9456],
         [0.7342, 0.6645, 0.8483, 0.7807],
         [0.9056, 0.6747, 0.7115, 0.4019]]])
torch.Size([2, 3, 4])


(tensor([[[0.6284, 0.0808, 0.8971, 0.6637],
          [0.6571, 0.1105, 0.9925, 0.9456]],
 
         [[0.9646, 0.8398, 0.2106, 0.5712],
          [0.7342, 0.6645, 0.8483, 0.7807]],
 
         [[0.2331, 0.9309, 0.0588, 0.7270],
          [0.9056, 0.6747, 0.7115, 0.4019]]]),
 torch.Size([3, 2, 4]))

In [ ]:
#both variables will share same memory on permuting hence changing a specific value in one will affect the other
x = torch.rand(1, 2, 3)
print(x)
y = x.permute(1, 2, 0) # (2, 3, 1)
print(y)
x[0, 0, 0] = 0.4
print(y)

tensor([[[0.6091, 0.4212, 0.0295],
         [0.1414, 0.2281, 0.9365]]])
tensor([[[0.6091],
         [0.4212],
         [0.0295]],

        [[0.1414],
         [0.2281],
         [0.9365]]])
tensor([[[0.4000],
         [0.4212],
         [0.0295]],

        [[0.1414],
         [0.2281],
         [0.9365]]])
